#!/bin/bash

# User Management Script

function add_user() {
    read -p "Enter username to add: " username
    sudo adduser "$username"
}

function delete_user() {
    read -p "Enter username to delete: " username
    sudo deluser "$username"
}

function list_users() {
    echo "System Users:"
    cut -d: -f1 /etc/passwd
}

function main() {
    echo "User  Management"
    echo "1. Add User"
    echo "2. Delete User"
    echo "3. List Users"
    echo "4. Exit"
    read -p "Choose an option: " option

    case $option in
        1) add_user ;;
        2) delete_user ;;
        3) list_users ;;
        4) exit 0 ;;
        *) echo "Invalid option." ;;
    esac
}

main